//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/SP_Campaign/Input/Player_Input_Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player_Input_Actions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player_Input_Actions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player_Input_Actions"",
    ""maps"": [
        {
            ""name"": ""Player_Actions"",
            ""id"": ""a893b6fa-ed69-4c0f-b336-d75846057ecf"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""3db98e16-7f36-4914-995f-d3abce1f7085"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""8989aa98-444f-4f87-835a-a4f0be78e5ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""cc9f883d-472a-47e0-adec-7fd75c2da7b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""1654fa83-2602-4419-8bc8-ee9316f6e403"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(pressPoint=1.401298E-45,behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch_Hold"",
                    ""type"": ""Value"",
                    ""id"": ""ed1f1508-f2b7-4f9a-84a3-7f9cd42a6112"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""e3d0a6a7-68e4-4168-be16-a47a6f0ed013"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fire"",
                    ""type"": ""Button"",
                    ""id"": ""d8fa8240-4354-46a0-a46c-1e37b13800a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ADS"",
                    ""type"": ""Button"",
                    ""id"": ""786353fe-eadb-4dcb-aa73-0026cbf462e0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon1"",
                    ""type"": ""Button"",
                    ""id"": ""3074f378-dbe2-4c06-85af-ba100b85ff7c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Weapon2"",
                    ""type"": ""Button"",
                    ""id"": ""2a9c1552-7b69-43bf-9e7c-eec1e6de5639"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Next_Weapon"",
                    ""type"": ""Button"",
                    ""id"": ""de4c5696-1554-4382-b4aa-f416af57f6fc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""e0dc9208-3cc9-4360-8ee4-467a921540b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""1d2ba55a-3578-4c92-9cc3-dbf472267d22"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""69356091-f13b-4058-9b34-f341c322cd13"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""455d376d-764f-4b97-a419-795b81554323"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bd1606eb-535a-4bd7-bc29-4742f1d21e0e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d0f834da-13c4-44b2-852e-4f8f87b4d1ca"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c8303453-2f10-451c-9861-32945ff7589f"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f8a1dff-a35e-42f3-89e7-a692e608d48f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b5d8062-7830-430d-b13c-3a8b526f42c1"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90861f10-a0cb-47df-8cfd-675a3aba60c4"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2988559b-878c-406d-93e6-88470fe5631f"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13380bf3-9995-4116-9492-84ea7e3e35d5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de84127d-4c55-448f-b6ba-08ed3f07c44f"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b27be87e-b326-4f75-b750-154f1617cc67"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41ec1907-a90a-4412-9708-9b1bc45a67f2"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd455870-7fc4-415b-b3aa-514b5a91b382"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fire"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d61471fd-96b0-42b9-a89d-1bcddd3d9f5e"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch_Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d52c14f7-a415-4ecf-9ea3-047f03524737"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c62fb911-1961-4a9d-9575-98219d3dbc65"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bcd65608-cfbe-4f4d-8416-1d9b8df65556"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ADS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6518a6a4-ad83-42c2-a8fd-2c8b93375ae3"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ADS"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86a48035-ce52-4497-9f9f-056cd90c8ea4"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Next_Weapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05ecafc2-3534-4ffc-b4ed-7662140dd4eb"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Weapon1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7513f9d3-5526-46a6-8ace-5570b57695a4"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9b95ecf-214e-42f1-a01b-96de8683cac5"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""224e99c1-44c1-4b18-8229-5a9c4e2283b6"",
            ""actions"": [
                {
                    ""name"": ""New action"",
                    ""type"": ""Button"",
                    ""id"": ""dde3bb5b-de90-4076-97fb-b3923f028326"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""138906c6-c37b-48eb-a49b-dd6c2bfe6a4d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""New action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player_Actions
        m_Player_Actions = asset.FindActionMap("Player_Actions", throwIfNotFound: true);
        m_Player_Actions_Move = m_Player_Actions.FindAction("Move", throwIfNotFound: true);
        m_Player_Actions_Run = m_Player_Actions.FindAction("Run", throwIfNotFound: true);
        m_Player_Actions_Jump = m_Player_Actions.FindAction("Jump", throwIfNotFound: true);
        m_Player_Actions_Crouch = m_Player_Actions.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Actions_Crouch_Hold = m_Player_Actions.FindAction("Crouch_Hold", throwIfNotFound: true);
        m_Player_Actions_Look = m_Player_Actions.FindAction("Look", throwIfNotFound: true);
        m_Player_Actions_Fire = m_Player_Actions.FindAction("Fire", throwIfNotFound: true);
        m_Player_Actions_ADS = m_Player_Actions.FindAction("ADS", throwIfNotFound: true);
        m_Player_Actions_Weapon1 = m_Player_Actions.FindAction("Weapon1", throwIfNotFound: true);
        m_Player_Actions_Weapon2 = m_Player_Actions.FindAction("Weapon2", throwIfNotFound: true);
        m_Player_Actions_Next_Weapon = m_Player_Actions.FindAction("Next_Weapon", throwIfNotFound: true);
        m_Player_Actions_Reload = m_Player_Actions.FindAction("Reload", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Newaction = m_UI.FindAction("New action", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_Actions
    private readonly InputActionMap m_Player_Actions;
    private IPlayer_ActionsActions m_Player_ActionsActionsCallbackInterface;
    private readonly InputAction m_Player_Actions_Move;
    private readonly InputAction m_Player_Actions_Run;
    private readonly InputAction m_Player_Actions_Jump;
    private readonly InputAction m_Player_Actions_Crouch;
    private readonly InputAction m_Player_Actions_Crouch_Hold;
    private readonly InputAction m_Player_Actions_Look;
    private readonly InputAction m_Player_Actions_Fire;
    private readonly InputAction m_Player_Actions_ADS;
    private readonly InputAction m_Player_Actions_Weapon1;
    private readonly InputAction m_Player_Actions_Weapon2;
    private readonly InputAction m_Player_Actions_Next_Weapon;
    private readonly InputAction m_Player_Actions_Reload;
    public struct Player_ActionsActions
    {
        private @Player_Input_Actions m_Wrapper;
        public Player_ActionsActions(@Player_Input_Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Actions_Move;
        public InputAction @Run => m_Wrapper.m_Player_Actions_Run;
        public InputAction @Jump => m_Wrapper.m_Player_Actions_Jump;
        public InputAction @Crouch => m_Wrapper.m_Player_Actions_Crouch;
        public InputAction @Crouch_Hold => m_Wrapper.m_Player_Actions_Crouch_Hold;
        public InputAction @Look => m_Wrapper.m_Player_Actions_Look;
        public InputAction @Fire => m_Wrapper.m_Player_Actions_Fire;
        public InputAction @ADS => m_Wrapper.m_Player_Actions_ADS;
        public InputAction @Weapon1 => m_Wrapper.m_Player_Actions_Weapon1;
        public InputAction @Weapon2 => m_Wrapper.m_Player_Actions_Weapon2;
        public InputAction @Next_Weapon => m_Wrapper.m_Player_Actions_Next_Weapon;
        public InputAction @Reload => m_Wrapper.m_Player_Actions_Reload;
        public InputActionMap Get() { return m_Wrapper.m_Player_Actions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_ActionsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayer_ActionsActions instance)
        {
            if (m_Wrapper.m_Player_ActionsActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnMove;
                @Run.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnRun;
                @Jump.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnJump;
                @Crouch.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnCrouch;
                @Crouch_Hold.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnCrouch_Hold;
                @Crouch_Hold.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnCrouch_Hold;
                @Crouch_Hold.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnCrouch_Hold;
                @Look.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnLook;
                @Fire.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnFire;
                @Fire.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnFire;
                @Fire.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnFire;
                @ADS.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnADS;
                @ADS.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnADS;
                @ADS.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnADS;
                @Weapon1.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnWeapon1;
                @Weapon1.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnWeapon1;
                @Weapon1.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnWeapon1;
                @Weapon2.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnWeapon2;
                @Weapon2.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnWeapon2;
                @Weapon2.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnWeapon2;
                @Next_Weapon.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnNext_Weapon;
                @Next_Weapon.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnNext_Weapon;
                @Next_Weapon.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnNext_Weapon;
                @Reload.started -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnReload;
                @Reload.performed -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnReload;
                @Reload.canceled -= m_Wrapper.m_Player_ActionsActionsCallbackInterface.OnReload;
            }
            m_Wrapper.m_Player_ActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Crouch_Hold.started += instance.OnCrouch_Hold;
                @Crouch_Hold.performed += instance.OnCrouch_Hold;
                @Crouch_Hold.canceled += instance.OnCrouch_Hold;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @Fire.started += instance.OnFire;
                @Fire.performed += instance.OnFire;
                @Fire.canceled += instance.OnFire;
                @ADS.started += instance.OnADS;
                @ADS.performed += instance.OnADS;
                @ADS.canceled += instance.OnADS;
                @Weapon1.started += instance.OnWeapon1;
                @Weapon1.performed += instance.OnWeapon1;
                @Weapon1.canceled += instance.OnWeapon1;
                @Weapon2.started += instance.OnWeapon2;
                @Weapon2.performed += instance.OnWeapon2;
                @Weapon2.canceled += instance.OnWeapon2;
                @Next_Weapon.started += instance.OnNext_Weapon;
                @Next_Weapon.performed += instance.OnNext_Weapon;
                @Next_Weapon.canceled += instance.OnNext_Weapon;
                @Reload.started += instance.OnReload;
                @Reload.performed += instance.OnReload;
                @Reload.canceled += instance.OnReload;
            }
        }
    }
    public Player_ActionsActions @Player_Actions => new Player_ActionsActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Newaction;
    public struct UIActions
    {
        private @Player_Input_Actions m_Wrapper;
        public UIActions(@Player_Input_Actions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Newaction => m_Wrapper.m_UI_Newaction;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Newaction.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNewaction;
                @Newaction.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNewaction;
                @Newaction.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNewaction;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Newaction.started += instance.OnNewaction;
                @Newaction.performed += instance.OnNewaction;
                @Newaction.canceled += instance.OnNewaction;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    public interface IPlayer_ActionsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnCrouch_Hold(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnFire(InputAction.CallbackContext context);
        void OnADS(InputAction.CallbackContext context);
        void OnWeapon1(InputAction.CallbackContext context);
        void OnWeapon2(InputAction.CallbackContext context);
        void OnNext_Weapon(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNewaction(InputAction.CallbackContext context);
    }
}
